import type { Metadata } from "next";
import "../globals.css";
import { Topbar } from "../components/topbar";
import { Sidebar } from "../components/sidebar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
    <body className="antialiased flex h-screen flex-col">
      {/* Header */}
      <header>
        <Topbar />
      </header>

      {/* Main Content */}
      <div className="flex flex-1">
        <Sidebar />
        <main className="flex-1 bg-gray-100 p-4 overflow-auto">
          {children}
        </main>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-white p-4 text-center">
        © 2024 Orygen
      </footer>
    </body>
  </html>
  );
}
